name: release-and-publish

on:
  push:
    tags: ["v*"] # push a tag like v1.2.3
  workflow_dispatch:

permissions:
  contents: write # create GitHub Releases
  id-token: write # OIDC for npm trusted publishing/provenance
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with: { version: 9 }

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: "https://registry.npmjs.org"
          cache: "pnpm"

      - run: pnpm install --frozen-lockfile
      - run: pnpm -s test --if-present
      - run: pnpm -s build --if-present

      - name: Verify tag equals package.json version
        run: |
          PKG_VERSION=$(node -p "require('./package.json').version")
          TAG="${GITHUB_REF_NAME#v}"
          [ "$PKG_VERSION" = "$TAG" ] || { echo "::error::Tag v$TAG != package.json $PKG_VERSION"; exit 1; }

      # With trusted publishing, provenance is attached automatically.
      # Keep --access public for a scoped package's first publish.
      - name: Publish to npm
        env:
          NPM_CONFIG_PROVENANCE: "true" # harmless; ensures attestation
        run: pnpm publish --access public

      - name: Create GitHub Release (auto notes)
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: gh release create "$GITHUB_REF_NAME" --generate-notes
