name: release-and-publish

on:
  push:
    branches: [main]
    paths:
      - package.json
  workflow_dispatch:

permissions:
  contents: write
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with: { version: 9 }
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org
          cache: pnpm

      - run: pnpm install --frozen-lockfile
      - run: pnpm -s build
      - run: pnpm -s test --if-present

      # ✅ Required: npm >= 11.5.1 for Trusted Publishing
      - run: npm i -g npm@latest

      - name: Publish
        env:
          NPM_CONFIG_PROVENANCE: "true"
        run: npm publish --access public
